config/routes.rb
Rails.application.routes.draw do
  resources :cvs
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cv.rb
class Cv < ApplicationRecord
  belongs_to :user

  validates :link, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :cvs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  before_action :set_cv, only: [:show, :edit, :update, :destroy]

  # GET /cvs
  # GET /cvs.json
  def index
    @cvs = Cv.all
  end

  # GET /cvs/1
  # GET /cvs/1.json
  def show
  end

  # GET /cvs/new
  def new
    @cv = Cv.new
  end

  # GET /cvs/1/edit
  def edit
  end

  # POST /cvs
  # POST /cvs.json
  def create
    @cv = Cv.new(cv_params)
    
    if @cv.save
      redirect_to @cv, notice: 'CV was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cvs/1
  # PATCH/PUT /cvs/1.json
  def update
    respond_to do |format|
      if @cv.update(cv_params)
        format.html { redirect_to @cv, notice: 'Cv was successfully updated.' }
        format.json { render :show, status: :ok, location: @cv }
      else
        format.html { render :edit }
        format.json { render json: @cv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cvs/1
  # DELETE /cvs/1.json
  def destroy
    @cv.destroy
    respond_to do |format|
      format.html { redirect_to cvs_url, notice: 'Cv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cv
      @cv = Cv.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cv_params
      params.require(:cv).permit(:link, :state, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cvs_helper.rb
module CvsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cvs/_form.html.erb
<%= form_with(model: cv, local: true) do |form| %>
  <% if cv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cv.errors.count, "error") %> prohibited this cv from being saved:</h2>

      <ul>
        <% cv.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cvs/edit.html.erb
<h1>Editing Cv</h1>

<%= render 'form', cv: @cv %>

<%= link_to 'Show', @cv %> |
<%= link_to 'Back', cvs_path %>

app/views/cvs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cvs</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>State</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cvs.each do |cv| %>
      <tr>
        <td><%= cv.link %></td>
        <td><%= cv.state %></td>
        <td><%= cv.user_id %></td>
        <td><%= link_to 'Show', cv %></td>
        <td><%= link_to 'Edit', edit_cv_path(cv) %></td>
        <td><%= link_to 'Destroy', cv, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cv', new_cv_path %>

app/views/cvs/new.html.erb
<h1>New Cv</h1>

<%= render 'form', cv: @cv %>

<%= link_to 'Back', cvs_path %>

app/views/cvs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @cv.link %>
</p>

<p>
  <strong>State:</strong>
  <%= @cv.state %>
</p>

<p>
  <strong>User:</strong>
  <%= @cv.user_id %>
</p>

<%= link_to 'Edit', edit_cv_path(@cv) %> |
<%= link_to 'Back', cvs_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HexletCv</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>